(function () {
    "use strict"

    window.App.SerialSeasons = [{
                     season: '1' + 'сезон',
                     episode: '1' + 'серия',
                     seasonNum: '1',
                     episodeNum: '1', 
                     id: '1211428&1&1',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '2' + 'серия',
                     seasonNum: '1',
                     episodeNum: '2', 
                     id: '1211428&1&2',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '3' + 'серия',
                     seasonNum: '1',
                     episodeNum: '3', 
                     id: '1211428&1&3',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '4' + 'серия',
                     seasonNum: '1',
                     episodeNum: '4', 
                     id: '1211428&1&4',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '5' + 'серия',
                     seasonNum: '1',
                     episodeNum: '5', 
                     id: '1211428&1&5',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '6' + 'серия',
                     seasonNum: '1',
                     episodeNum: '6', 
                     id: '1211428&1&6',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '7' + 'серия',
                     seasonNum: '1',
                     episodeNum: '7', 
                     id: '1211428&1&7',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '8' + 'серия',
                     seasonNum: '1',
                     episodeNum: '8', 
                     id: '1211428&1&8',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '9' + 'серия',
                     seasonNum: '1',
                     episodeNum: '9', 
                     id: '1211428&1&9',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '10' + 'серия',
                     seasonNum: '1',
                     episodeNum: '10', 
                     id: '1211428&1&10',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '11' + 'серия',
                     seasonNum: '1',
                     episodeNum: '11', 
                     id: '1211428&1&11',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '12' + 'серия',
                     seasonNum: '1',
                     episodeNum: '12', 
                     id: '1211428&1&12',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '1' + 'серия',
                     seasonNum: '2',
                     episodeNum: '1', 
                     id: '1211428&2&1',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '2' + 'серия',
                     seasonNum: '2',
                     episodeNum: '2', 
                     id: '1211428&2&2',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '3' + 'серия',
                     seasonNum: '2',
                     episodeNum: '3', 
                     id: '1211428&2&3',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '4' + 'серия',
                     seasonNum: '2',
                     episodeNum: '4', 
                     id: '1211428&2&4',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '5' + 'серия',
                     seasonNum: '2',
                     episodeNum: '5', 
                     id: '1211428&2&5',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '6' + 'серия',
                     seasonNum: '2',
                     episodeNum: '6', 
                     id: '1211428&2&6',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '7' + 'серия',
                     seasonNum: '2',
                     episodeNum: '7', 
                     id: '1211428&2&7',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '8' + 'серия',
                     seasonNum: '2',
                     episodeNum: '8', 
                     id: '1211428&2&8',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '9' + 'серия',
                     seasonNum: '2',
                     episodeNum: '9', 
                     id: '1211428&2&9',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '10' + 'серия',
                     seasonNum: '2',
                     episodeNum: '10', 
                     id: '1211428&2&10',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '11' + 'серия',
                     seasonNum: '2',
                     episodeNum: '11', 
                     id: '1211428&2&11',
                     name: 'Isekai Quartet',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '12' + 'серия',
                     seasonNum: '2',
                     episodeNum: '12', 
                     id: '1211428&2&12',
                     name: 'Isekai Quartet',
                  },
          ]
  })();
  