(function () {
    "use strict" // страница создана в файле index.js

    window.App.SerialSeasons = [{
                     season: '1' + 'сезон',
                     episode: '1' + 'серия',
                     seasonNum: '1',
                     episodeNum: '1', 
                     id: '1161904&1&1',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '2' + 'серия',
                     seasonNum: '1',
                     episodeNum: '2', 
                     id: '1161904&1&2',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '3' + 'серия',
                     seasonNum: '1',
                     episodeNum: '3', 
                     id: '1161904&1&3',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '4' + 'серия',
                     seasonNum: '1',
                     episodeNum: '4', 
                     id: '1161904&1&4',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '5' + 'серия',
                     seasonNum: '1',
                     episodeNum: '5', 
                     id: '1161904&1&5',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '6' + 'серия',
                     seasonNum: '1',
                     episodeNum: '6', 
                     id: '1161904&1&6',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '7' + 'серия',
                     seasonNum: '1',
                     episodeNum: '7', 
                     id: '1161904&1&7',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '8' + 'серия',
                     seasonNum: '1',
                     episodeNum: '8', 
                     id: '1161904&1&8',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '9' + 'серия',
                     seasonNum: '1',
                     episodeNum: '9', 
                     id: '1161904&1&9',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '10' + 'серия',
                     seasonNum: '1',
                     episodeNum: '10', 
                     id: '1161904&1&10',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '11' + 'серия',
                     seasonNum: '1',
                     episodeNum: '11', 
                     id: '1161904&1&11',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '12' + 'серия',
                     seasonNum: '1',
                     episodeNum: '12', 
                     id: '1161904&1&12',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '1' + 'серия',
                     seasonNum: '2',
                     episodeNum: '1', 
                     id: '1161904&2&1',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '2' + 'серия',
                     seasonNum: '2',
                     episodeNum: '2', 
                     id: '1161904&2&2',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '3' + 'серия',
                     seasonNum: '2',
                     episodeNum: '3', 
                     id: '1161904&2&3',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '4' + 'серия',
                     seasonNum: '2',
                     episodeNum: '4', 
                     id: '1161904&2&4',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '5' + 'серия',
                     seasonNum: '2',
                     episodeNum: '5', 
                     id: '1161904&2&5',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '6' + 'серия',
                     seasonNum: '2',
                     episodeNum: '6', 
                     id: '1161904&2&6',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '7' + 'серия',
                     seasonNum: '2',
                     episodeNum: '7', 
                     id: '1161904&2&7',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '8' + 'серия',
                     seasonNum: '2',
                     episodeNum: '8', 
                     id: '1161904&2&8',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '9' + 'серия',
                     seasonNum: '2',
                     episodeNum: '9', 
                     id: '1161904&2&9',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '10' + 'серия',
                     seasonNum: '2',
                     episodeNum: '10', 
                     id: '1161904&2&10',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '11' + 'серия',
                     seasonNum: '2',
                     episodeNum: '11', 
                     id: '1161904&2&11',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '12' + 'серия',
                     seasonNum: '2',
                     episodeNum: '12', 
                     id: '1161904&2&12',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '1' + 'серия',
                     seasonNum: '3',
                     episodeNum: '1', 
                     id: '1161904&3&1',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '2' + 'серия',
                     seasonNum: '3',
                     episodeNum: '2', 
                     id: '1161904&3&2',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '3' + 'серия',
                     seasonNum: '3',
                     episodeNum: '3', 
                     id: '1161904&3&3',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '4' + 'серия',
                     seasonNum: '3',
                     episodeNum: '4', 
                     id: '1161904&3&4',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '5' + 'серия',
                     seasonNum: '3',
                     episodeNum: '5', 
                     id: '1161904&3&5',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '6' + 'серия',
                     seasonNum: '3',
                     episodeNum: '6', 
                     id: '1161904&3&6',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '7' + 'серия',
                     seasonNum: '3',
                     episodeNum: '7', 
                     id: '1161904&3&7',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '8' + 'серия',
                     seasonNum: '3',
                     episodeNum: '8', 
                     id: '1161904&3&8',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '9' + 'серия',
                     seasonNum: '3',
                     episodeNum: '9', 
                     id: '1161904&3&9',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '10' + 'серия',
                     seasonNum: '3',
                     episodeNum: '10', 
                     id: '1161904&3&10',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '11' + 'серия',
                     seasonNum: '3',
                     episodeNum: '11', 
                     id: '1161904&3&11',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '12' + 'серия',
                     seasonNum: '3',
                     episodeNum: '12', 
                     id: '1161904&3&12',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '4' + 'сезон',
                     episode: '1' + 'серия',
                     seasonNum: '4',
                     episodeNum: '1', 
                     id: '1161904&4&1',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '4' + 'сезон',
                     episode: '2' + 'серия',
                     seasonNum: '4',
                     episodeNum: '2', 
                     id: '1161904&4&2',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '4' + 'сезон',
                     episode: '3' + 'серия',
                     seasonNum: '4',
                     episodeNum: '3', 
                     id: '1161904&4&3',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '4' + 'сезон',
                     episode: '4' + 'серия',
                     seasonNum: '4',
                     episodeNum: '4', 
                     id: '1161904&4&4',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '4' + 'сезон',
                     episode: '5' + 'серия',
                     seasonNum: '4',
                     episodeNum: '5', 
                     id: '1161904&4&5',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '4' + 'сезон',
                     episode: '6' + 'серия',
                     seasonNum: '4',
                     episodeNum: '6', 
                     id: '1161904&4&6',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '4' + 'сезон',
                     episode: '7' + 'серия',
                     seasonNum: '4',
                     episodeNum: '7', 
                     id: '1161904&4&7',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '4' + 'сезон',
                     episode: '8' + 'серия',
                     seasonNum: '4',
                     episodeNum: '8', 
                     id: '1161904&4&8',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '4' + 'сезон',
                     episode: '9' + 'серия',
                     seasonNum: '4',
                     episodeNum: '9', 
                     id: '1161904&4&9',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '4' + 'сезон',
                     episode: '10' + 'серия',
                     seasonNum: '4',
                     episodeNum: '10', 
                     id: '1161904&4&10',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '4' + 'сезон',
                     episode: '11' + 'серия',
                     seasonNum: '4',
                     episodeNum: '11', 
                     id: '1161904&4&11',
                     name: 'Golden Kamuy',
                  },
          {
                     season: '4' + 'сезон',
                     episode: '12' + 'серия',
                     seasonNum: '4',
                     episodeNum: '12', 
                     id: '1161904&4&12',
                     name: 'Golden Kamuy',
                  },
          ]
  })();
  