(function () {
    "use strict"

    window.App.SerialSeasons = [{
                     season: '1' + 'сезон',
                     episode: '1' + 'серия',
                     seasonNum: '1',
                     episodeNum: '1', 
                     id: '1316617&1&1',
                     name: 'Superman and Lois',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '2' + 'серия',
                     seasonNum: '1',
                     episodeNum: '2', 
                     id: '1316617&1&2',
                     name: 'Superman and Lois',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '3' + 'серия',
                     seasonNum: '1',
                     episodeNum: '3', 
                     id: '1316617&1&3',
                     name: 'Superman and Lois',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '4' + 'серия',
                     seasonNum: '1',
                     episodeNum: '4', 
                     id: '1316617&1&4',
                     name: 'Superman and Lois',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '5' + 'серия',
                     seasonNum: '1',
                     episodeNum: '5', 
                     id: '1316617&1&5',
                     name: 'Superman and Lois',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '6' + 'серия',
                     seasonNum: '1',
                     episodeNum: '6', 
                     id: '1316617&1&6',
                     name: 'Superman and Lois',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '7' + 'серия',
                     seasonNum: '1',
                     episodeNum: '7', 
                     id: '1316617&1&7',
                     name: 'Superman and Lois',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '8' + 'серия',
                     seasonNum: '1',
                     episodeNum: '8', 
                     id: '1316617&1&8',
                     name: 'Superman and Lois',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '9' + 'серия',
                     seasonNum: '1',
                     episodeNum: '9', 
                     id: '1316617&1&9',
                     name: 'Superman and Lois',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '10' + 'серия',
                     seasonNum: '1',
                     episodeNum: '10', 
                     id: '1316617&1&10',
                     name: 'Superman and Lois',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '11' + 'серия',
                     seasonNum: '1',
                     episodeNum: '11', 
                     id: '1316617&1&11',
                     name: 'Superman and Lois',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '12' + 'серия',
                     seasonNum: '1',
                     episodeNum: '12', 
                     id: '1316617&1&12',
                     name: 'Superman and Lois',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '13' + 'серия',
                     seasonNum: '1',
                     episodeNum: '13', 
                     id: '1316617&1&13',
                     name: 'Superman and Lois',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '14' + 'серия',
                     seasonNum: '1',
                     episodeNum: '14', 
                     id: '1316617&1&14',
                     name: 'Superman and Lois',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '15' + 'серия',
                     seasonNum: '1',
                     episodeNum: '15', 
                     id: '1316617&1&15',
                     name: 'Superman and Lois',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '16' + 'серия',
                     seasonNum: '1',
                     episodeNum: '16', 
                     id: '1316617&1&16',
                     name: 'Superman and Lois',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '1' + 'серия',
                     seasonNum: '2',
                     episodeNum: '1', 
                     id: '1316617&2&1',
                     name: 'Superman and Lois',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '2' + 'серия',
                     seasonNum: '2',
                     episodeNum: '2', 
                     id: '1316617&2&2',
                     name: 'Superman and Lois',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '3' + 'серия',
                     seasonNum: '2',
                     episodeNum: '3', 
                     id: '1316617&2&3',
                     name: 'Superman and Lois',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '4' + 'серия',
                     seasonNum: '2',
                     episodeNum: '4', 
                     id: '1316617&2&4',
                     name: 'Superman and Lois',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '5' + 'серия',
                     seasonNum: '2',
                     episodeNum: '5', 
                     id: '1316617&2&5',
                     name: 'Superman and Lois',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '6' + 'серия',
                     seasonNum: '2',
                     episodeNum: '6', 
                     id: '1316617&2&6',
                     name: 'Superman and Lois',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '7' + 'серия',
                     seasonNum: '2',
                     episodeNum: '7', 
                     id: '1316617&2&7',
                     name: 'Superman and Lois',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '8' + 'серия',
                     seasonNum: '2',
                     episodeNum: '8', 
                     id: '1316617&2&8',
                     name: 'Superman and Lois',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '9' + 'серия',
                     seasonNum: '2',
                     episodeNum: '9', 
                     id: '1316617&2&9',
                     name: 'Superman and Lois',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '10' + 'серия',
                     seasonNum: '2',
                     episodeNum: '10', 
                     id: '1316617&2&10',
                     name: 'Superman and Lois',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '11' + 'серия',
                     seasonNum: '2',
                     episodeNum: '11', 
                     id: '1316617&2&11',
                     name: 'Superman and Lois',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '12' + 'серия',
                     seasonNum: '2',
                     episodeNum: '12', 
                     id: '1316617&2&12',
                     name: 'Superman and Lois',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '13' + 'серия',
                     seasonNum: '2',
                     episodeNum: '13', 
                     id: '1316617&2&13',
                     name: 'Superman and Lois',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '14' + 'серия',
                     seasonNum: '2',
                     episodeNum: '14', 
                     id: '1316617&2&14',
                     name: 'Superman and Lois',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '15' + 'серия',
                     seasonNum: '2',
                     episodeNum: '15', 
                     id: '1316617&2&15',
                     name: 'Superman and Lois',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '1' + 'серия',
                     seasonNum: '3',
                     episodeNum: '1', 
                     id: '1316617&3&1',
                     name: 'Superman and Lois',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '2' + 'серия',
                     seasonNum: '3',
                     episodeNum: '2', 
                     id: '1316617&3&2',
                     name: 'Superman and Lois',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '3' + 'серия',
                     seasonNum: '3',
                     episodeNum: '3', 
                     id: '1316617&3&3',
                     name: 'Superman and Lois',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '4' + 'серия',
                     seasonNum: '3',
                     episodeNum: '4', 
                     id: '1316617&3&4',
                     name: 'Superman and Lois',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '5' + 'серия',
                     seasonNum: '3',
                     episodeNum: '5', 
                     id: '1316617&3&5',
                     name: 'Superman and Lois',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '6' + 'серия',
                     seasonNum: '3',
                     episodeNum: '6', 
                     id: '1316617&3&6',
                     name: 'Superman and Lois',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '7' + 'серия',
                     seasonNum: '3',
                     episodeNum: '7', 
                     id: '1316617&3&7',
                     name: 'Superman and Lois',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '8' + 'серия',
                     seasonNum: '3',
                     episodeNum: '8', 
                     id: '1316617&3&8',
                     name: 'Superman and Lois',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '9' + 'серия',
                     seasonNum: '3',
                     episodeNum: '9', 
                     id: '1316617&3&9',
                     name: 'Superman and Lois',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '10' + 'серия',
                     seasonNum: '3',
                     episodeNum: '10', 
                     id: '1316617&3&10',
                     name: 'Superman and Lois',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '11' + 'серия',
                     seasonNum: '3',
                     episodeNum: '11', 
                     id: '1316617&3&11',
                     name: 'Superman and Lois',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '12' + 'серия',
                     seasonNum: '3',
                     episodeNum: '12', 
                     id: '1316617&3&12',
                     name: 'Superman and Lois',
                  },
          ]
  })();
  