(function () {
    "use strict"

    window.App.animeSerialSeasons = [{
                     season: '1' + 'сезон',
                     episode: '1' + 'серия',
                     seasonNum: '1',
                     episodeNum: '1', 
                     id: '1177503&1&1',
                     name: 'Ultraman',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '2' + 'серия',
                     seasonNum: '1',
                     episodeNum: '2', 
                     id: '1177503&1&2',
                     name: 'Ultraman',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '3' + 'серия',
                     seasonNum: '1',
                     episodeNum: '3', 
                     id: '1177503&1&3',
                     name: 'Ultraman',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '4' + 'серия',
                     seasonNum: '1',
                     episodeNum: '4', 
                     id: '1177503&1&4',
                     name: 'Ultraman',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '5' + 'серия',
                     seasonNum: '1',
                     episodeNum: '5', 
                     id: '1177503&1&5',
                     name: 'Ultraman',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '6' + 'серия',
                     seasonNum: '1',
                     episodeNum: '6', 
                     id: '1177503&1&6',
                     name: 'Ultraman',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '7' + 'серия',
                     seasonNum: '1',
                     episodeNum: '7', 
                     id: '1177503&1&7',
                     name: 'Ultraman',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '8' + 'серия',
                     seasonNum: '1',
                     episodeNum: '8', 
                     id: '1177503&1&8',
                     name: 'Ultraman',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '9' + 'серия',
                     seasonNum: '1',
                     episodeNum: '9', 
                     id: '1177503&1&9',
                     name: 'Ultraman',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '10' + 'серия',
                     seasonNum: '1',
                     episodeNum: '10', 
                     id: '1177503&1&10',
                     name: 'Ultraman',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '11' + 'серия',
                     seasonNum: '1',
                     episodeNum: '11', 
                     id: '1177503&1&11',
                     name: 'Ultraman',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '12' + 'серия',
                     seasonNum: '1',
                     episodeNum: '12', 
                     id: '1177503&1&12',
                     name: 'Ultraman',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '13' + 'серия',
                     seasonNum: '1',
                     episodeNum: '13', 
                     id: '1177503&1&13',
                     name: 'Ultraman',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '1' + 'серия',
                     seasonNum: '2',
                     episodeNum: '1', 
                     id: '1177503&2&1',
                     name: 'Ultraman',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '2' + 'серия',
                     seasonNum: '2',
                     episodeNum: '2', 
                     id: '1177503&2&2',
                     name: 'Ultraman',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '3' + 'серия',
                     seasonNum: '2',
                     episodeNum: '3', 
                     id: '1177503&2&3',
                     name: 'Ultraman',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '4' + 'серия',
                     seasonNum: '2',
                     episodeNum: '4', 
                     id: '1177503&2&4',
                     name: 'Ultraman',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '5' + 'серия',
                     seasonNum: '2',
                     episodeNum: '5', 
                     id: '1177503&2&5',
                     name: 'Ultraman',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '6' + 'серия',
                     seasonNum: '2',
                     episodeNum: '6', 
                     id: '1177503&2&6',
                     name: 'Ultraman',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '1' + 'серия',
                     seasonNum: '3',
                     episodeNum: '1', 
                     id: '1177503&3&1',
                     name: 'Ultraman',
                  },
          ]
  })();
  