(function () {
    "use strict"

    window.App.animeSerialSeasons = [{
                     season: '1' + 'сезон',
                     episode: '1' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '2' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '3' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '4' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '5' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '6' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '7' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '8' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '9' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '10' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '11' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '12' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '13' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '14' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '15' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '16' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '17' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '18' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '19' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '20' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '21' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '22' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '23' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '24' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '1' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '2' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '3' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '4' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '5' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '6' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '7' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '8' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '9' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '10' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '11' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '12' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '13' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '14' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '15' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '16' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '17' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '18' + 'серия',
                     id: '1274280',
                     name: 'Vinland Saga',
                  },
          ]
  })();
  