(function () {
    "use strict"

    window.App.animeSerialSeasons = [{
                     season: '1' + 'сезон',
                     episode: '1' + 'серия',
                     seasonNum: '1',
                     episodeNum: '1', 
                     id: '1249511&1&1',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '2' + 'серия',
                     seasonNum: '1',
                     episodeNum: '2', 
                     id: '1249511&1&2',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '3' + 'серия',
                     seasonNum: '1',
                     episodeNum: '3', 
                     id: '1249511&1&3',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '4' + 'серия',
                     seasonNum: '1',
                     episodeNum: '4', 
                     id: '1249511&1&4',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '5' + 'серия',
                     seasonNum: '1',
                     episodeNum: '5', 
                     id: '1249511&1&5',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '6' + 'серия',
                     seasonNum: '1',
                     episodeNum: '6', 
                     id: '1249511&1&6',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '7' + 'серия',
                     seasonNum: '1',
                     episodeNum: '7', 
                     id: '1249511&1&7',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '8' + 'серия',
                     seasonNum: '1',
                     episodeNum: '8', 
                     id: '1249511&1&8',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '9' + 'серия',
                     seasonNum: '1',
                     episodeNum: '9', 
                     id: '1249511&1&9',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '10' + 'серия',
                     seasonNum: '1',
                     episodeNum: '10', 
                     id: '1249511&1&10',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '11' + 'серия',
                     seasonNum: '1',
                     episodeNum: '11', 
                     id: '1249511&1&11',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '12' + 'серия',
                     seasonNum: '1',
                     episodeNum: '12', 
                     id: '1249511&1&12',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '13' + 'серия',
                     seasonNum: '1',
                     episodeNum: '13', 
                     id: '1249511&1&13',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '14' + 'серия',
                     seasonNum: '1',
                     episodeNum: '14', 
                     id: '1249511&1&14',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '15' + 'серия',
                     seasonNum: '1',
                     episodeNum: '15', 
                     id: '1249511&1&15',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '16' + 'серия',
                     seasonNum: '1',
                     episodeNum: '16', 
                     id: '1249511&1&16',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '17' + 'серия',
                     seasonNum: '1',
                     episodeNum: '17', 
                     id: '1249511&1&17',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '18' + 'серия',
                     seasonNum: '1',
                     episodeNum: '18', 
                     id: '1249511&1&18',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '19' + 'серия',
                     seasonNum: '1',
                     episodeNum: '19', 
                     id: '1249511&1&19',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '20' + 'серия',
                     seasonNum: '1',
                     episodeNum: '20', 
                     id: '1249511&1&20',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '21' + 'серия',
                     seasonNum: '1',
                     episodeNum: '21', 
                     id: '1249511&1&21',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '22' + 'серия',
                     seasonNum: '1',
                     episodeNum: '22', 
                     id: '1249511&1&22',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '23' + 'серия',
                     seasonNum: '1',
                     episodeNum: '23', 
                     id: '1249511&1&23',
                     name: 'Dr. Stone',
                  },
          {
                     season: '1' + 'сезон',
                     episode: '24' + 'серия',
                     seasonNum: '1',
                     episodeNum: '24', 
                     id: '1249511&1&24',
                     name: 'Dr. Stone',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '1' + 'серия',
                     seasonNum: '2',
                     episodeNum: '1', 
                     id: '1249511&2&1',
                     name: 'Dr. Stone',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '2' + 'серия',
                     seasonNum: '2',
                     episodeNum: '2', 
                     id: '1249511&2&2',
                     name: 'Dr. Stone',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '3' + 'серия',
                     seasonNum: '2',
                     episodeNum: '3', 
                     id: '1249511&2&3',
                     name: 'Dr. Stone',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '4' + 'серия',
                     seasonNum: '2',
                     episodeNum: '4', 
                     id: '1249511&2&4',
                     name: 'Dr. Stone',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '5' + 'серия',
                     seasonNum: '2',
                     episodeNum: '5', 
                     id: '1249511&2&5',
                     name: 'Dr. Stone',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '6' + 'серия',
                     seasonNum: '2',
                     episodeNum: '6', 
                     id: '1249511&2&6',
                     name: 'Dr. Stone',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '7' + 'серия',
                     seasonNum: '2',
                     episodeNum: '7', 
                     id: '1249511&2&7',
                     name: 'Dr. Stone',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '8' + 'серия',
                     seasonNum: '2',
                     episodeNum: '8', 
                     id: '1249511&2&8',
                     name: 'Dr. Stone',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '9' + 'серия',
                     seasonNum: '2',
                     episodeNum: '9', 
                     id: '1249511&2&9',
                     name: 'Dr. Stone',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '10' + 'серия',
                     seasonNum: '2',
                     episodeNum: '10', 
                     id: '1249511&2&10',
                     name: 'Dr. Stone',
                  },
          {
                     season: '2' + 'сезон',
                     episode: '11' + 'серия',
                     seasonNum: '2',
                     episodeNum: '11', 
                     id: '1249511&2&11',
                     name: 'Dr. Stone',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '1' + 'серия',
                     seasonNum: '3',
                     episodeNum: '1', 
                     id: '1249511&3&1',
                     name: 'Dr. Stone',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '2' + 'серия',
                     seasonNum: '3',
                     episodeNum: '2', 
                     id: '1249511&3&2',
                     name: 'Dr. Stone',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '3' + 'серия',
                     seasonNum: '3',
                     episodeNum: '3', 
                     id: '1249511&3&3',
                     name: 'Dr. Stone',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '4' + 'серия',
                     seasonNum: '3',
                     episodeNum: '4', 
                     id: '1249511&3&4',
                     name: 'Dr. Stone',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '5' + 'серия',
                     seasonNum: '3',
                     episodeNum: '5', 
                     id: '1249511&3&5',
                     name: 'Dr. Stone',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '6' + 'серия',
                     seasonNum: '3',
                     episodeNum: '6', 
                     id: '1249511&3&6',
                     name: 'Dr. Stone',
                  },
          {
                     season: '3' + 'сезон',
                     episode: '7' + 'серия',
                     seasonNum: '3',
                     episodeNum: '7', 
                     id: '1249511&3&7',
                     name: 'Dr. Stone',
                  },
          ]
  })();
  