(function () {
    "use strict"

    window.App.serialSeasons = [{
                     season: '1' + 'сезон',
                     episode: '1' + 'серия',
                     seasonNum: '1',
                     episodeNum: '1', 
                     id: '229784&1&1',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '2' + 'серия',
                     seasonNum: '1',
                     episodeNum: '2', 
                     id: '229784&1&2',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '3' + 'серия',
                     seasonNum: '1',
                     episodeNum: '3', 
                     id: '229784&1&3',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '4' + 'серия',
                     seasonNum: '1',
                     episodeNum: '4', 
                     id: '229784&1&4',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '5' + 'серия',
                     seasonNum: '1',
                     episodeNum: '5', 
                     id: '229784&1&5',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '6' + 'серия',
                     seasonNum: '1',
                     episodeNum: '6', 
                     id: '229784&1&6',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '7' + 'серия',
                     seasonNum: '1',
                     episodeNum: '7', 
                     id: '229784&1&7',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '8' + 'серия',
                     seasonNum: '1',
                     episodeNum: '8', 
                     id: '229784&1&8',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '9' + 'серия',
                     seasonNum: '1',
                     episodeNum: '9', 
                     id: '229784&1&9',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '10' + 'серия',
                     seasonNum: '1',
                     episodeNum: '10', 
                     id: '229784&1&10',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '11' + 'серия',
                     seasonNum: '1',
                     episodeNum: '11', 
                     id: '229784&1&11',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '12' + 'серия',
                     seasonNum: '1',
                     episodeNum: '12', 
                     id: '229784&1&12',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '13' + 'серия',
                     seasonNum: '1',
                     episodeNum: '13', 
                     id: '229784&1&13',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '14' + 'серия',
                     seasonNum: '1',
                     episodeNum: '14', 
                     id: '229784&1&14',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '15' + 'серия',
                     seasonNum: '1',
                     episodeNum: '15', 
                     id: '229784&1&15',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '16' + 'серия',
                     seasonNum: '1',
                     episodeNum: '16', 
                     id: '229784&1&16',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '17' + 'серия',
                     seasonNum: '1',
                     episodeNum: '17', 
                     id: '229784&1&17',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '18' + 'серия',
                     seasonNum: '1',
                     episodeNum: '18', 
                     id: '229784&1&18',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '19' + 'серия',
                     seasonNum: '1',
                     episodeNum: '19', 
                     id: '229784&1&19',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '20' + 'серия',
                     seasonNum: '1',
                     episodeNum: '20', 
                     id: '229784&1&20',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '21' + 'серия',
                     seasonNum: '1',
                     episodeNum: '21', 
                     id: '229784&1&21',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '22' + 'серия',
                     seasonNum: '1',
                     episodeNum: '22', 
                     id: '229784&1&22',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '23' + 'серия',
                     seasonNum: '1',
                     episodeNum: '23', 
                     id: '229784&1&23',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '24' + 'серия',
                     seasonNum: '1',
                     episodeNum: '24', 
                     id: '229784&1&24',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '25' + 'серия',
                     seasonNum: '1',
                     episodeNum: '25', 
                     id: '229784&1&25',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '26' + 'серия',
                     seasonNum: '1',
                     episodeNum: '26', 
                     id: '229784&1&26',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '27' + 'серия',
                     seasonNum: '1',
                     episodeNum: '27', 
                     id: '229784&1&27',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '28' + 'серия',
                     seasonNum: '1',
                     episodeNum: '28', 
                     id: '229784&1&28',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '29' + 'серия',
                     seasonNum: '1',
                     episodeNum: '29', 
                     id: '229784&1&29',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '30' + 'серия',
                     seasonNum: '1',
                     episodeNum: '30', 
                     id: '229784&1&30',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '31' + 'серия',
                     seasonNum: '1',
                     episodeNum: '31', 
                     id: '229784&1&31',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '32' + 'серия',
                     seasonNum: '1',
                     episodeNum: '32', 
                     id: '229784&1&32',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '33' + 'серия',
                     seasonNum: '1',
                     episodeNum: '33', 
                     id: '229784&1&33',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '34' + 'серия',
                     seasonNum: '1',
                     episodeNum: '34', 
                     id: '229784&1&34',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '35' + 'серия',
                     seasonNum: '1',
                     episodeNum: '35', 
                     id: '229784&1&35',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '36' + 'серия',
                     seasonNum: '1',
                     episodeNum: '36', 
                     id: '229784&1&36',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '37' + 'серия',
                     seasonNum: '1',
                     episodeNum: '37', 
                     id: '229784&1&37',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '38' + 'серия',
                     seasonNum: '1',
                     episodeNum: '38', 
                     id: '229784&1&38',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '39' + 'серия',
                     seasonNum: '1',
                     episodeNum: '39', 
                     id: '229784&1&39',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '40' + 'серия',
                     seasonNum: '1',
                     episodeNum: '40', 
                     id: '229784&1&40',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '41' + 'серия',
                     seasonNum: '1',
                     episodeNum: '41', 
                     id: '229784&1&41',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '42' + 'серия',
                     seasonNum: '1',
                     episodeNum: '42', 
                     id: '229784&1&42',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '43' + 'серия',
                     seasonNum: '1',
                     episodeNum: '43', 
                     id: '229784&1&43',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '44' + 'серия',
                     seasonNum: '1',
                     episodeNum: '44', 
                     id: '229784&1&44',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '45' + 'серия',
                     seasonNum: '1',
                     episodeNum: '45', 
                     id: '229784&1&45',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '46' + 'серия',
                     seasonNum: '1',
                     episodeNum: '46', 
                     id: '229784&1&46',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '47' + 'серия',
                     seasonNum: '1',
                     episodeNum: '47', 
                     id: '229784&1&47',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '48' + 'серия',
                     seasonNum: '1',
                     episodeNum: '48', 
                     id: '229784&1&48',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '1' + 'сезон',
                     episode: '49' + 'серия',
                     seasonNum: '1',
                     episodeNum: '49', 
                     id: '229784&1&49',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '2' + 'сезон',
                     episode: '1' + 'серия',
                     seasonNum: '2',
                     episodeNum: '1', 
                     id: '229784&2&1',
                     name: `Transformer: Super Link`,
                  },
          {
                     season: '2' + 'сезон',
                     episode: '2' + 'серия',
                     seasonNum: '2',
                     episodeNum: '2', 
                     id: '229784&2&2',
                     name: `Transformer: Super Link`,
                  },
          ]
  })();
  